Repository bluealloy/revm, pull requests merged in 2024-04, with the labels that each got.

#1269 chore(ci): use more stable rust toolchain plugin
  .github/workflows/cachegrind.yml
Labels: ci

#1286 feat: add `Bytecode::original_byte_slice`
  crates/primitives/src/bytecode.rs
  crates/primitives/src/bytecode/legacy.rs
Labels: feature

#1327 Implement `with_chain_id` for `CfgEnv`
  crates/primitives/src/env.rs
Labels: feature

#1359 fix: return the correct error in resize_memory
  crates/interpreter/src/instructions/macros.rs
  crates/revm/src/builder.rs
Labels: bug

#1353 Add uniswap V2 WETH-USDC swap example
  Cargo.lock
  crates/revm/Cargo.toml
  examples/uniswap_v2_usdc_swap.rs
Labels: feature
