Repository bluealloy/revm, pull requests merged in 2024-05, with the labels that each got.

#1354 feat: implement EIP-2935
  crates/interpreter/src/instructions/host.rs
  crates/interpreter/src/instructions/macros.rs
  crates/interpreter/src/opcode.rs
  crates/primitives/src/constants.rs
Labels: feature, hf-prague

#1387 feat(precompile): add Prague hardfork specification
  crates/precompile/src/lib.rs
Labels: feature, hf-prague

#1392 fix(precompile): inherit Prague precompiles from Cancun
  crates/precompile/src/lib.rs
Labels: bug, hf-prague

#1432 fix(precompile): ignore infinity points in G1 MSM
  crates/precompile/src/bls12_381/g1_msm.rs
  crates/precompile/src/bls12_381/g2_msm.rs
Labels: bug, hf-prague

#1446 chore: add docs for BLS scalar input decoding
  crates/precompile/src/bls12_381/utils.rs
Labels: hf-prague

#1434 fix: check canonical Fp elements
  crates/precompile/src/bls12_381.rs
  crates/precompile/src/bls12_381/g1.rs
  crates/precompile/src/bls12_381/g1_msm.rs
  crates/precompile/src/bls12_381/g1_mul.rs
  crates/precompile/src/bls12_381/g2.rs
  crates/precompile/src/bls12_381/g2_msm.rs
  crates/precompile/src/bls12_381/map_fp2_to_g2.rs
  crates/precompile/src/bls12_381/map_fp_to_g1.rs
  crates/precompile/src/bls12_381/utils.rs
  crates/precompile/test-vectors/fail-add_G1_bls.json
  crates/precompile/test-vectors/fail-add_G2_bls.json
  crates/precompile/test-vectors/fail-map_fp2_to_G2_bls.json
  crates/precompile/test-vectors/fail-map_fp_to_G1_bls.json
  crates/precompile/test-vectors/fail-mul_G1_bls.json
  crates/precompile/test-vectors/fail-mul_G2_bls.json
  crates/precompile/test-vectors/fail-multiexp_G1_bls.json
  crates/precompile/test-vectors/fail-multiexp_G2_bls.json
  crates/precompile/test-vectors/fail-pairing_check_bls.json
Labels: bug, hf-prague
